import { Inter } from "@next/font/google";
import Head from "next/head";
import Converter from "../components/Converter";
import Converter2 from "../components/Converter2";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" mt-12 flex justify-center items-center">
        <Converter />
      </div>
      <div className=" flex justify-center items-center flex-col">
        <Converter2 />
      </div>
    </>
  );
}
